[variables]
NODE_OPTIONS = "--max-old-space-size=4096"

[phases.setup]
nixPkgs = [
    'php84',
    'php84Extensions.intl',
    'php84Extensions.mbstring',
    'php84Extensions.pdo',
    'php84Extensions.pdo_mysql',
    'php84Extensions.pdo_pgsql',
    'php84Extensions.gd',
    'php84Extensions.fileinfo',
    'nodejs_22'
    "mkdir -p .frankenphp/conf.d",
    "cp php.ini .frankenphp/conf.d/uploads.ini"
]

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-scripts --no-interaction',
    'npm ci --include=dev || npm install --include=dev'
]

[phases.build]
cmds = [
    'cp php.ini /etc/php.ini',
    'npm run build',
    'chmod -R 777 storage bootstrap/cache',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan storage:link'
]

[start]
cmd = 'php -c /etc/php.ini artisan serve --host=0.0.0.0 --port=$PORT'
